language: node_js
node_js:
  - 'iojs-v2.3.4'
before_install:
  - npm install -g npm@3
  - npm config set loglevel error
  - npm config -g list -l
  - npm --version
script: npm run-script ci
cache:
  directories:
    - node_modules
# Post build notifications to the Integrations Flowdock
notifications:
  flowdock: e3dc17bc8a2c1b3412abe3e5747f8291

env:
  - CI=1 MONGODB_VERSION=2.6.x MONGODB_TOPOLOGY=standalone
  # - CI=1 MONGODB_VERSION=3.0.x MONGODB_TOPOLOGY=standalone
  # - CI=1 MONGODB_VERSION=3.1.x MONGODB_TOPOLOGY=standalone
  # - CI=1 MONGODB_VERSION=2.6.x MONGODB_TOPOLOGY=replicaset
  # - CI=1 MONGODB_VERSION=3.0.x MONGODB_TOPOLOGY=replicaset
  # - CI=1 MONGODB_VERSION=3.1.x MONGODB_TOPOLOGY=replicaset
  # - CI=1 MONGODB_VERSION=2.6.x MONGODB_TOPOLOGY=cluster
  # - CI=1 MONGODB_VERSION=3.0.x MONGODB_TOPOLOGY=cluster
  # - CI=1 MONGODB_VERSION=3.1.x MONGODB_TOPOLOGY=cluster
