# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      # Standalone deps
      - dependency-name: "mongodb"
      - dependency-name: "bson"
      # All the mongosh deps
      - dependency-name: "@mongosh/node-runtime-worker-thread"
      - dependency-name: "@mongosh/browser-repl"
      - dependency-name: "@mongosh/logging"
      # All the electron and its related deps
      - dependency-name: "electron"
      - dependency-name: "@electron/remote"
      - dependency-name: "@electron/rebuild"
      - dependency-name: "browserslist"
      - dependency-name: "node-abi"
      # All the devtools-shared packages https://github.com/mongodb-js/devtools-shared
      - dependency-name: "@mongodb-js/dl-center"
      - dependency-name: "@mongodb-js/get-os-info"
      - dependency-name: "@mongodb-js/mongodb-constants"
      - dependency-name: "@mongodb-js/mongodb-downloader"
      - dependency-name: "mongodb-runner"
      - dependency-name: "@mongodb-js/monorepo-tools"
      - dependency-name: "@mongodb-js/oidc-mock-provider"
      - dependency-name: "@mongodb-js/sbom-tools"
    groups:
      electron:
        patterns:
        - "electron"
        - "@electron/remote"
        - "@electron/rebuild"
        - "browserslist"
        - "node-abi"
        update-types: ["minor", "patch"]
      devtools-shared:
        patterns:
        - "@mongodb-js/dl-center"
        - "@mongodb-js/get-os-info"
        - "@mongodb-js/mongodb-constants"
        - "@mongodb-js/mongodb-downloader"
        - "mongodb-runner"
        - "@mongodb-js/monorepo-tools"
        - "@mongodb-js/oidc-mock-provider"
        - "@mongodb-js/sbom-tools"
      mongosh:
        patterns:
        - "@mongosh/*"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"