sudo: false
dist: trusty
language: node_js
node_js:
  - 10.2.1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libkrb5-dev
      - xvfb
      - libsecret-1-dev
      - gnome-keyring
      - python-gnomekeyring
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_install:
  - npm i -g npm@latest
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc
install:
  - npm ci
cache: npm
script:
  - npm run check
  - npm run cover
  - npm run test:karma
