sudo: false
dist: trusty
language: node_js
node_js:
  - 6
script: npm run-script ci
cache:
  # TODO (imlucas) We can't use yarn just yet on travis until an upstream
  # fix is landed for https://github.com/yarnpkg/yarn/pull/2164
  # yarn: true
  directories:
    - node_modules
    - $HOME/.electron
addons:
  apt:
    packages:
      - rpm
      # TODO (imlucas) @see https://github.com/mongodb-js/hadron-build/pull/45
      # - lintian
