version: '3'

services:
  mongodb-tls-server:
    image: mongo
    ports:
      - "27029:27017"
    volumes:
      - "./mongod-server.conf:/etc/mongod.conf:ro"
      - "./tls:/etc/mongod/tls:ro"
    command: [ "mongod", "--bind_ip_all", "--config", "/etc/mongod.conf" ]

  mongodb-tls-server-client:
    image: mongo
    ports:
      - "27030:27017"
    volumes:
      - "./mongod-server-client.conf:/etc/mongod.conf:ro"
      - "./tls:/etc/mongod/tls:ro"
    command: [ "mongod", "--bind_ip_all", "--config", "/etc/mongod.conf" ]

  mongodb-tls-x509:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27031:27017"
    volumes:
      - "./mongod-x509.conf:/etc/mongod.conf:ro"
      - "./tls:/etc/mongod/tls:ro"
      - "./initdb-x509:/docker-entrypoint-initdb.d/"
    command: [ "mongod", "--bind_ip_all", "--config", "/etc/mongod.conf" ]
