sudo: false
dist: trusty
language: node_js
node_js:
  - 10.2.1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libkrb5-dev
      - xvfb
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_install:
  - npm i -g npm@latest
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc
install:
  - npm ci
cache: npm
script: 
  - npm run cover 
  - npm run test:karma
after_success:
  - npm run storybook:ghpages
  - rm .npmrc
deploy:
  # Push to GitHub Pages
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN 
    keep-history: true
    local_dir: .ghpages
    on:
      branch: 3.0.0
  # TODO (@imlucas) Do we even need to do this?
  # All we're doing is making sure webpack can 
  # build (for the 4th time)
  # - provider: script
  #   script: npm run compile
  #   on:
  #     branch: master