language: node_js
sudo: required
node_js:
  - 8.9.3
script: npm run-script ci
cache:
  directories:
  - node_modules
notifications:
  flowdock: e3dc17bc8a2c1b3412abe3e5747f8291
env:
  - MONGODB_VERSION=3.2.x MONGODB_TOPOLOGY=standalone
  - MONGODB_VERSION=3.4.x MONGODB_TOPOLOGY=standalone
