# This action runs lint checks and tests against the code.
name: Check and Test

# Controls when the action will run.
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MAIN_BRANCH_NAME: remotes/origin/main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-and-test:
    name: Check and Test

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

      fail-fast: false

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Deps Ubuntu
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get -y install libkrb5-dev libsecret-1-dev net-tools libstdc++6 gnome-keyring

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2.1.2
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: ^12.4.0

      - name: Install npm@7
        run: npm install -g npm@7

      - name: Install Dependencies
        run: |
          npm install --force
          # Dependencies are included when installing as npm workspaces will
          # hoist every package in the repo and it's important that the
          # dependencies of packages we are planning to test are also prepared
          npx lerna run prepare --stream --since $MAIN_BRANCH_NAME --include-dependencies
        shell: bash

      - name: Run Checks on root folder
        # Checks for dependencies issues in the root folder and for dependency
        # alignment
        run: npm run depcheck
        shell: bash

      - name: Run Checks
        # We exclude dependents when running eslint and depchecks because
        # linting and dependency checking is relevant only for packages where
        # the source code was changed
        run: npm run check-ci -- --stream --since $MAIN_BRANCH_NAME --exclude-dependents
        shell: bash

      - name: Run Tests
        run: npm run test-ci -- --stream --since $MAIN_BRANCH_NAME
        shell: bash
