# This action runs lint checks and tests against the code.
name: Check and Test

# Controls when the action will run.
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MAIN_BRANCH_NAME: remotes/origin/main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-and-test:
    name: Check and Test

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

      fail-fast: false

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Deps Ubuntu
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get -y install libkrb5-dev libsecret-1-dev net-tools libstdc++6 gnome-keyring

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: ^14.17.5
          cache: 'npm'

      - name: Install npm@7
        run: npm install -g npm@7

      - name: Install Dependencies
        run: |
          npm ci
          # Dependencies are included when installing as npm workspaces will
          # hoist every package in the repo and it's important that the
          # dependencies of packages we are planning to test are also prepared
          npx lerna run bootstrap --stream --since $MAIN_BRANCH_NAME --include-dependencies
        shell: bash

      - name: Run Checks
        # We exclude dependents when running eslint and depchecks because
        # linting and dependency checking is relevant only for packages where
        # the source code was changed
        run: npm run check-ci -- --stream --since $MAIN_BRANCH_NAME --exclude-dependents
        shell: bash

      - name: Run Tests
        env:
          E2E_TESTS_ATLAS_HOST: ${{ secrets.E2E_TESTS_ATLAS_HOST }}
          E2E_TESTS_ATLAS_USERNAME: ${{ secrets.E2E_TESTS_ATLAS_USERNAME }}
          E2E_TESTS_ATLAS_PASSWORD: ${{ secrets.E2E_TESTS_ATLAS_PASSWORD }}
          # Matches what we are doing in Evergreen
          MONGODB_VERSION: '4'
          DEBUG: 'compass-e2e-tests*'
        run: npm run test-ci -- --stream --since $MAIN_BRANCH_NAME
        shell: bash

      - name: Upload Spectron Logs
        uses: actions/upload-artifact@v2
        if: ${{ cancelled() || failure() }}
        with:
          name: Spectron Debug Files ${{ github.workflow }} ${{ runner.os }}
          path: packages/compass-e2e-tests/.log/**/*
