# Run e2e tests on osx since in EVG are currently disabled due
# to issues with unlocking keytar.
name: E2e Tests OSX

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    name: Package and Run E2e Tests on OSX

    timeout-minutes: 45

    strategy:
      matrix:
        os: [macos-latest]

      fail-fast: false

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # So we are not in a detached HEAD state and have a user ready, so that
      # lerna can commit later on
      - name: Prepare Git
        run: |
          git switch -c "compass-build-workflow"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: ^14.17.5
          cache: 'npm'

      - name: Install npm@8.3.1
        run: |
          npm install -g npm@8.3.1

      - name: Run node-gyp bug workaround script
        run: |
          bash .evergreen/node-gyp-bug-workaround.sh

      - name: Install Dependencies
        run: |
          npm -v
          npm ci
          # We don't need to bootstrap anything else before running the e2e tests
          npx lerna run bootstrap -- --stream --scope @mongodb/webpack-config-compass

      - name: Build Compass
        env:
          DEBUG: 'hadron*,mongo*,electron*'
        run: npm run package-compass

      - name: Test Packaged Application
        env:
          E2E_TESTS_METRICS_URI: ${{ secrets.E2E_TESTS_METRICS_URI }}
          E2E_TESTS_ATLAS_HOST: ${{ secrets.E2E_TESTS_ATLAS_HOST }}
          E2E_TESTS_DATA_LAKE_HOST: ${{ secrets.E2E_TESTS_DATA_LAKE_HOST }}
          E2E_TESTS_ANALYTICS_NODE_HOST: ${{ secrets.E2E_TESTS_ANALYTICS_NODE_HOST }}
          E2E_TESTS_SERVERLESS_HOST: ${{ secrets.E2E_TESTS_SERVERLESS_HOST }}
          E2E_TESTS_FREE_TIER_HOST: ${{ secrets.E2E_TESTS_FREE_TIER_HOST }}
          E2E_TESTS_ATLAS_USERNAME: ${{ secrets.E2E_TESTS_ATLAS_USERNAME }}
          E2E_TESTS_ATLAS_PASSWORD: ${{ secrets.E2E_TESTS_ATLAS_PASSWORD }}
          E2E_TESTS_ATLAS_X509_PEM: ${{ secrets.E2E_TESTS_ATLAS_X509_PEM }}
          E2E_TESTS_ATLAS_IAM_ACCESS_KEY_ID: ${{ secrets.E2E_TESTS_ATLAS_IAM_ACCESS_KEY_ID }}
          E2E_TESTS_ATLAS_IAM_SECRET_ACCESS_KEY: ${{ secrets.E2E_TESTS_ATLAS_IAM_SECRET_ACCESS_KEY }}
          E2E_TESTS_ATLAS_IAM_TEMP_ROLE_ARN: ${{ secrets.E2E_TESTS_ATLAS_IAM_TEMP_ROLE_ARN }}
          E2E_TESTS_ATLAS_IAM_USER_ARN: ${{ secrets.E2E_TESTS_ATLAS_IAM_USER_ARN }}
          # Matches what we are doing in Evergreen
          MONGODB_VERSION: '4'
          DEBUG: 'compass-e2e-tests*,hadron*'
        run: npm run test-packaged-ci --workspace compass-e2e-tests

      - name: Upload Compass Artifacts
        uses: actions/upload-artifact@v2
        # In case e2e tests failed, but assets were produced, we still want to
        # upload them for inspection
        if: always()
        with:
          name: Compass Build ${{ runner.os }}
          path: |
            packages/compass/dist/*.dmg
            packages/compass/dist/*.zip
            packages/compass/dist/*.exe
            packages/compass/dist/*.msi
            packages/compass/dist/*.deb
            packages/compass/dist/*.rpm
            packages/compass/dist/*.tar.gz
            packages/compass/dist/*.json

      - name: Upload Webdriverio Logs
        uses: actions/upload-artifact@v2
        # even if tests succeeded you might still want to examine logs
        if: always()
        with:
          name: Webdriverio Debug Files ${{ github.workflow }} ${{ runner.os }}
          path: packages/compass-e2e-tests/.log/**/*